### ISSUE TITLE
is generative ai training a child of ai-training?

### ISSUE THREAD

**Issue by paul2keller** [lrosenthol/opt-out-vocab#1]
I am a bit surprised to see that Generative AI training is shown as a subset of AI training. This makes a lot of sense to me (and I had it that way on my original slide), but I had understood that during the WS Leonard had objected to this approach and we had decided instead to go for a set of well-defined use cases that are independently addressable. I am still fine with having these two nested, but I would like to understand the rationale for this change.

**Comment by lrosenthol** [comment]
I thought we had agreed on the hierarchy - but I am more than happy to go back to separate items...

**Comment by sposth** [comment]
To avoid confusion and ensure clear communication of opt-out preferences:
Each opt-out option should be independently selectable. The options should not automatically include/exclude other options. I think that it makes sense that creators explicitly specify each option they want to opt-out from. A hierarchy with automatic inclusions has to be fully understood, otherwise it can lead to unintended selections. On the recipient side, a hierarchy must also be interpreted, and this interpretation may be prone to error.

**Comment by paul2keller** [comment]
@sposth your comment does not apply to the overarching `TDM` category, correct? 

If this is the case I think we are all aligned that we want each of the more specific uses cases to be independently selectable. so `ai-training` is a child of `tdm` but NOT a child of `generative-ai-training`. it operates on the same level of hierarchy as `ai-training`

**Comment by lrosenthol** [comment]
Agreed.  I have made this change in the latest draft, so I am going to close this issue.
